// board 목록 요청하기
export const REQUEST_BOARD_LIST = "REQUEST_BOARD_LIST"
export const SUCCESS_BOARD_LIST = "SUCCESS_BOARD_LIST"
export const FAILURE_BOARD_LIST = "FAILURE_BOARD_LIST"

export const REQUEST_BOARD_POST = "REQUEST_BOARD_POST"
export const SUCCESS_BOARD_POST = "SUCCESS_BOARD_POST"
export const FAILURE_BOARD_POST = "FAILURE_BOARD_POST"

export const REQUEST_BOARD_DETAIL = "REQUEST_BOARD_DETAIL"
export const SUCCESS_BOARD_DETAIL = "SUCCESS_BOARD_DETAIL"
export const FAILURE_BOARD_DETAIL = "FAILURE_BOARD_DETAIL"

export const REQUEST_BOARD_MODIFY = "REQUEST_BOARD_MODIFY"
export const SUCCESS_BOARD_MODIFY = "SUCCESS_BOARD_MODIFY"
export const FAILURE_BOARD_MODIFY = "FAILURE_BOARD_MODIFY"

export const REQUEST_BOARD_DELETE = "REQUEST_BOARD_DELETE"
export const SUCCESS_BOARD_DELETE = "SUCCESS_BOARD_DELETE"
export const FAILURE_BOARD_DELETE = "FAILURE_BOARD_DELETE"