server:
  servlet:
    context-path: /example
  port: 8088
  error:
    whitelabel:
      enabled: false
    path: /error

spring:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/boardKotlin
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
    dbcp2:
      validation-query: SELECT 1
    jndi-name: java:jboss/datasources/KeycloakDS
      pool
  jpa:
    open-in-view: false

  devtools:
    livereload:
      enabled: true
